name: Docker build & push
on:
  push:
    tags:
      - v*
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Upload to Docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tiemonl/best_buy_monitor:latest,tiemonl/best_buy_monitor:${{ steps.get_tag.outputs.TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
