name: Docker build & push
on:
  push:
    tags:
      - v*
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Docker
        uses: docker/build-push-action@v1
        with:
          repository: tiemonl/best_buy_monitor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_ref: true
